#! /bin/sh
# Build an executable compitable with Centos 7 / Amazon Linux 2
podman build -t woodpecker-pat-builder .
podman run -v $HOME/.cargo/registry:/root/.cargo/registry -v $PWD:$PWD -w $PWD -it woodpecker-pat-builder cargo build --workspace --release
strip target/release/woodpecker-pat
